from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

# !!!! SELECT MODE !!!!
MODE = "DEVELOPEMENT"


# Clear all positions and orderds
ABORT_ALL_POSITIONS = True

# Find cointegrated pairs
FIND_COINTEGRATED = False

# Manage exits
MANAGE_EXITS = True

# Place trades
PLACE_TRADES = True

# Resolution
RESOLUTION = "1HOUR"

# Stats Window --> calculates a rolling moving average of prices based on this period
WINDOW = 21 

# Tresholds - Opening
MAX_HALF_LIFE = 24
ZSCORE_TRESH = 1.5
USD_PER_TRADE = 50   #!!!!!!!! USE KELLY CRITERION TO CALCULATE THIS PARAMETER !!!!!! 
USD_MIN_COLLATERAL = 1800

# Tresholds - Closing
CLOSE_AT_ZSCORE_SCORE = True

# Ethereum Address
ETHEREUM_ADDRESS = "0xbE72D0Efd0261A6fBe6E01e24572a8AB900A6A3D"

# KEYS - Production
# Needed for mainnet
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# KEYS - Developement
# Needed for testnet
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# KEYS - Export
STARK_PRIVATE_KEY= STARK_PRIVATE_KEY_MAINNET if MODE=="PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY= DYDX_API_KEY_MAINNET if MODE=="PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET= DYDX_API_SECRET_MAINNET if MODE=="PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE= DYDX_API_PASSPHRASE_MAINNET if MODE=="PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

# HOST - Export
HOST = API_HOST_MAINNET if MODE=="PRODUCTION" else API_HOST_GOERLI

# HTTP PROVIDER
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/CwKTAfOUhVWanDM1kEM-hKzAEcR5IlUd"
HTTP_PROVIDER_TESTNET = "https://eth-goerli.g.alchemy.com/v2/ALjwxbuzW3S_Jdu1pI_x0yHFzq5QuS4X"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE=="PRODUCTION" else HTTP_PROVIDER_TESTNET
